"""Initial migration

Revision ID: 813429847207
Revises: 
Create Date: 2023-05-29 02:35:02.577537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813429847207'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
